// Code generated by entc, DO NOT EDIT.

package user

import (
	"github.com/facebook/ent"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiscordID holds the string denoting the discordid field in the database.
	FieldDiscordID = "discord_id"
	// FieldGames holds the string denoting the games field in the database.
	FieldGames = "games"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldDiscordID,
	FieldGames,
	FieldPoints,
	FieldRating,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "iloMusiAko/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultGames holds the default value on creation for the Games field.
	DefaultGames uint64
	// DefaultPoints holds the default value on creation for the Points field.
	DefaultPoints uint64
	// DefaultRating holds the default value on creation for the Rating field.
	DefaultRating uint64
)
